### ISSUE TITLE
Do something with Kernel

### ISSUE THREAD

**Issue by ThesisNotIncluded** [Synapse-OS/SynapseOS#1]
I think we need to create c function to determine which kernel is loaded currently, or create wrapper that interacts with current version of kernel

**Comment by 0Nera** [comment]
Can be more? I need more details.

**Comment by ThesisNotIncluded** [comment]
i mean create function to determine which kernel architecture (16-bit, 32-bit and 64-bit) is loaded currently

**Comment by 0Nera** [comment]
> i mean create function to determine which kernel architecture (16-bit, 32-bit and 64-bit) is loaded currently

Ok. I think it can be done.
