### ISSUE TITLE
Will there ever be any support for building on Linux?

### ISSUE THREAD

**Issue by Blobadoodle** [Synapse-OS/SynapseOS#10]
As the title says i was wondering if you could either create a `build.sh` for building on Linux or maybe use a makefile to build?

**Comment by 0Nera** [comment]
We will be doing a linux build soon. By version 0006 I promise a working build.sh

**Comment by ThesisNotIncluded** [comment]
I recently fixed the ```build.sh``` file, and now you can build it on Linux (https://github.com/Synapse-OS/SynapseOS/pull/12)
