### ISSUE TITLE
"Time" and "hello" commands don't function as intended

### ISSUE THREAD

**Issue by Blobadoodle** [Synapse-OS/SynapseOS#11]
Ive tried this using qemu and [copy/v86](https://copy.sh/v86) and the `time` and `hello` commands do not seem to be functioning properly?

The time command simply returns "Hello World!" and the hello command simply returns a newline and no text.

Am i doing something wrong? Is the released iso corrupted?

Emulator: Qemu
CPU: AMD
arch: 64bits
Host OS: Linux Manjaro
![Screenshot from 2021-07-28 15-22-08](https://user-images.githubusercontent.com/50550651/127329781-84cd2d0a-3d73-4f34-bc10-c67bd3fff4b1.png)

**Comment by 0Nera** [comment]
Hello! Use last fix https://github.com/Synapse-OS/SynapseOS/releases/tag/0005.1
