### ISSUE TITLE
Define the marco to avoid explicitly optimizing structures

### ISSUE THREAD

**Issue by ThesisNotIncluded** [Synapse-OS/SynapseOS#14]
I've seen that you're defining ```__attribute__((packed))``` attribute explicitly, and in my opinion this is bad, because you need to write a whole attribute.

My solution is define a marco that association with ```__attribute__((packed))``` attribute in the base header for each '.c' file.

Something like
```c
// means prefer optimization
#define PREF_OPT __attribute__((packed))
```

**Comment by COTULARS** [comment]
Excuse me, could you please describe exactly what you mean?

**Comment by ThesisNotIncluded** [comment]
I mean define a macro and use it to optimize structure for compiler 🤔

**Comment by ThesisNotIncluded** [comment]
@0Nera it isn't bug and isn't project feature. it's just code feature
