### ISSUE TITLE
Little typo in README.md

### ISSUE THREAD

**Issue by ThesisNotIncluded** [Synapse-OS/SynapseOS#15]
![image](https://user-images.githubusercontent.com/51379496/128424877-e9ee41eb-ac0b-4b6e-ac66-86b3777f278d.png)

SinopseOS moment

**Comment by ThesisNotIncluded** [comment]
Forgot upload the link: https://github.com/Synapse-OS/SynapseOS/blob/main/README.md

**Comment by COTULARS** [comment]
Thanks for your attention, everything has already been fixed.
